language: php

php:
  - "5.4"

services:
  - mysql

env:
  - OPENSHIFT_MYSQL_DB_HOST=localhost OPENSHIFT_MYSQL_DB_PORT=3306 OPENSHIFT_MYSQL_DB_USERNAME=travis
    OPENSHIFT_MYSQL_DB_PASSWORD= OPENSHIFT_GEAR_NAME=ivta

before_script:
  # webserver setup
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
        # Selenium
  - wget http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar
  - java -jar selenium-server-standalone-2.46.0.jar > /dev/null &

  - php -S localhost:8000 index.php &
  # bootstrap with composer
  - composer self-update
  - composer install --no-interaction --prefer-source
  - git submodule update --init --recursive
  - mkdir application application/cache application/logs
  - chmod 777 application/cache application/logs
  # db setup
  - mysql -e 'create database ivta;'

script:
  - ./vendor/behat/behat/bin/behat --config behat.yml -p phantomjs-travis

deploy:
  provider: openshift
  user: dornathal
  password:
    secure: dU0eznU1Eh1RoBnSqWxXqaYDRy2PPH9FwnboYqSYRt4SSDMN+iRrdE80cu8CAgLy9an+9JV2MX/+Ii2NcyroRGy+JRFqBgY9wkiWt11SD/rqa8EKHlrjG4rzN6pk04i9lrnC8Ai7CHTaGpouC1uaIXCAH6sGEfmitQSptLiHvXCNdZEWwLfjtaDGk0tzAHPwgum7x4u2QOtqMyM3I8izU0lmAhNrgAiOXd62IFLcaak9pKG6opy7o4OQPA5ZjGX/MPN6jYtc6fJ3azxc8V4G+TF71kbWvbl1yry3OGa5yZrXnFbezOCh9y1BxOwjEsJXRZLL+HC8j0So3fueSnUqs4kx2yun5pg7SpVaGWqmrbnaCdZYIe1S1vxo4FiOVUz8aptxu3zY8JCD12xFLTT1tPHzyMozBx/XIJKj5HYikorH+zJaYpFVxa4dJnCxwdT7sB3+DqJUs0eJNJvxV8F8zsSNwXPG3OTvfcmOENhW0I1Y6/i7VyW7TFHWyERxEdgAOgf93+uhI+HFI/vw79PcGETFxfmPAfJTBgFQ0f+6u2OxvzFm0Qy3NAGJRWgL6WlAlUpjnkz+dG/LAVTi51PtUd88rEq4swUGxB/AHDhyQz2HhOwD6wcCzaPC4t+sVjgP0ZgeGYP8dIkpNNtbTVnRuK976Oppt5tTG+A7cwuQVas=
  app: ivta
  domain: dornathal
  on:
    repo: Dornathal/ivta